"use client"

import Head from 'next/head';
import { Share } from '@capacitor/share';

export default function Home() {
	const share = async () => {
		await Share.share({
			title: 'Simons YT Channel',
			text: 'Learn to build awesome mobile apps!',
			url: 'https://www.youtube.com/simongrimmdev_',
			dialogTitle: 'Share with friends'
		});
	};

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>
					Welcome to <a href="https://nextjs.org">Dupa!</a>
				</h1>
				<p>
					<h2>Cool channel</h2>
					<a onClick={() => share()}>Share now!</a>
				</p>
			</main>
		</div>
	);
}
